---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: color-game-challenge

resources:
  - resources/configmap.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/route.yaml
  - resources/apply-manifest.yaml
  - resources/buildah.yaml
  - resources/git-clone.yaml
  - resources/openshift-client.yaml
  - resources/pipeline.yaml
