---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: color-game-challenge
spec:
  params:
    - default: https://github.com/Caseraw/color-challenge.git
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: pipeline
      name: manifest_dir
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REVISION)
        - name: DELETE_EXISTING
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: apply-manifests 
      params:
        - name: manifest_dir
          value: $(params.manifest_dir)
      taskRef:
        name: apply-manifests
      workspaces:
      - name: source
        workspace: workspace
      runAfter: 
      - fetch-repository
  workspaces:
    - name: workspace
